### ISSUE TITLE
添加搜索引擎

### ISSUE THREAD

**Issue by calidion** [3gcnbeta/www#16]
直接可以搜索

**Comment by cdll** [comment]
一直以为还是静态页呢，哈哈，后端跑的什么语言啊？

**Comment by calidion** [comment]
是静态页。
搜索引擎直接跳转到相关的搜索引擎。

**Comment by cdll** [comment]
噗，这个方法也是6，哈哈哈，我还说建议你可以做spa呢~

**Comment by calidion** [comment]
呵呵。是SPA。
目前数据存在JSON里面了。
正考虑如何添加搜索引擎。
这个项目的主要目标就是将常用的地址放上来，方便工作。
