### ISSUE TITLE
字体坑爹

### ISSUE THREAD

**Issue by ghost** [3gcnbeta/www#17]
这种字体效果难以看清；
Web Server连lighttpd都没有；
然后连PHP全栈框架**Laravel**都没有。

**Comment by calidion** [comment]
@iVanilla 
如果有好的字体，可以PR提交。
有觉得需要添加的服务器也可以PR添加。
谢谢。

**Comment by ghost** [comment]
@calidion 我说的是字体的效果难以看清，并非字体本身难看。

**Comment by calidion** [comment]
@iVanilla 嗯。这个是设计问题。欢迎调整后PR给我。
