### ISSUE TITLE
JS后端或全栈框架可以增加一个socket.io

### ISSUE THREAD

**Issue by jovey-zheng** [3gcnbeta/www#5]
不会PR囧

```
{
  url: 'http://socket.io/',
  favicon: 'favicon.ico',
  name: 'socket.io'
}

```

**Comment by calidion** [comment]
好的。PR不难的。
1、先fork
2、添加你要添加的内容
3、commit到你fork的库里
4、通过库左上角的创建pull request按钮提交就可以了。
英文帮助：
https://help.github.com/articles/creating-a-pull-request/

**Comment by jovey-zheng** [comment]
@calidion 刚刚我试了一下，在mater下修改其中一个文件的一个内容，然后提交时有选择，选了第二个，会直接生成另一个分支并创建了PR，我能在自己fork里看到这个PR，不知道origin能不能看到。。

**Comment by calidion** [comment]
你需要先fork.然后在本地测试通过，再提交到你自己fork的代码库。然后在你的代码库里提交PR

**Comment by jovey-zheng** [comment]
@calidion 了解了。谢谢解答
